disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - force_try
  - nesting
  - todo
  - xctfail_message
  - orphaned_doc_comment
  - inclusive_language
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - file_header
  - multiline_parameters
  - vertical_parameter_alignment_on_call
  - unused_optional_binding
  - fallthrough
  - identifier_name
  - type_name
  - redundant_discardable_let
included:
  - Sources
excluded:
  - Sources/flow/protobuf
function_parameter_count:
  warning: 20
  error: 25
line_length:
  warning: 250
  error: 450
large_tuple:
  warning: 4
type_body_length:
  warning: 450
  error: 650
function_body_length: 80
file_length:
  warning: 600
  error: 1200
trailing_comma:
  mandatory_comma: true
identifier_name:
  min_length:
    2
  allowed_symbols: ["_"]
type_name:
  allowed_symbols: ["_"]
superfluous_disable_command: warning
reporter: "xcode"
