name: build-docs

on:
  push:
    branches:
      - master
  # release:
  #   types: [published]

jobs:
  build-docs:
    runs-on: macos-11
    # env:
    #   DEVELOPER_DIR: /Applications/Xcode_13.0.app

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: master

      - name: debug
        run: |
          pwd
          ls
          mkdir -p SourceTest
          touch SourceTest/testfile.txt
        working-directory: master

      # - name: Get tag
      #   id: vars
      #   run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      # - name: Setup ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 3.0.2
      #     bundler-cache: true

      # - name: Build doc
      #   run: |
      #     bundle install
      #     bundle exec jazzy --output .build/jazzy
      
      - name: Checkout doc
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: debug
        env:
          G_WORKSPACE: ${{github.workspace}}
        run: |
          pwd
          ls
          mkdir -p DestTest
          cp -R ${G_WORKSPACE}/master/SourceTest Dest
        working-directory: gh-pages

      # - name: Clean old doc
      #   run: |
      #     rm -rf docs/current

      # - name: Copy new doc
      #   env:
      #     RELEASE_VERSION: ${{steps.vars.outputs.tag}}
      #   run: |
      #     mkdir -p docs/current
      #     mkdir -p docs/$RELEASE_VERSION
      #     cp -R .build/jazzy/* docs/current
      #     cp -R .build/jazzy/* docs/$RELEASE_VERSION

      - name: Commit
        # env:
        #   RELEASE_VERSION: ${{steps.vars.outputs.tag}}
        # git commit -am "Generate ${RELEASE_VERSION} docs automatically"
        run: |
          git config user.name CI
          git config user.email CI@ci.com
          git add .
          git commit -m "test commit"
          git push
        working-directory: gh-pages