name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    
    defaults:
      run:
        working-directory: TestPackage

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: swift build -v

    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      env:
        WORKING_DIRECTORY: TestPackage
      
    - name: Run tests
      run: swift test -v
