name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    
    defaults:
      run:
        working-directory: TestPackage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - name: Build documents
        run: bundle exec jazzy
      
      # - name: Build
      #   run: swift build -v
        
      # - name: Run tests
      #   run: swift test -v




  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: norio-nomura/action-swiftlint@3.2.1
  #       env:
  #         WORKING_DIRECTORY: TestPackage
