name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    
    defaults:
      run:
        working-directory: TestPackage

    steps:
      - uses: actions/checkout@v2
      
      # - name: Build
      #   run: swift build -v
        
      # - name: Run tests
      #   run: swift test -v

      - name: SwiftPM Jazzy Docs
        uses: sersoft-gmbh/swifty-docs-action@v1.2.1
        with:
          clean: true


  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: norio-nomura/action-swiftlint@3.2.1
  #       env:
  #         WORKING_DIRECTORY: TestPackage
