name: build-docs

on:
  release:
    types: [published]

jobs:
  build-docs:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.app

    defaults:
      run:
        working-directory: TestPackage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      # - name: Debug print
      #   env:
      #     RELEASE_VERSION: ${{steps.vars.outputs.tag}}
      #   run: |
      #     echo $RELEASE_VERSION
      #     echo ${{steps.vars.outputs.tag}}

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - name: Build doc
        run: |
          bundle install
          bundle exec jazzy --output .build/jazzy
      
      - name: Checkout doc
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Clean old doc
        run: |
          rm -rf docs/current

      - name: Copy new doc
        env:
          RELEASE_VERSION: ${{steps.vars.outputs.tag}}
        run: |
          mkdir -p docs/current
          mkdir -p docs/$RELEASE_VERSION
          cp -R .build/jazzy/* docs/current
          cp -R .build/jazzy/* docs/$RELEASE_VERSION

      - name: Commit
        env:
          RELEASE_VERSION: ${{steps.vars.outputs.tag}}
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'CI@ci.com'
          git commit -am "Generate ${RELEASE_VERSION} docs automatically"
          git push
      
      # - name: Build
      #   run: swift build -v
        
      # - name: Run tests
      #   run: swift test -v




  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: norio-nomura/action-swiftlint@3.2.1
  #       env:
  #         WORKING_DIRECTORY: TestPackage
